### ISSUE TITLE
Add this feature to TUfast TU Dresden

### ISSUE THREAD

**Issue by OliEfr** [spyfly/videocampus-sachsen-downloader#1]
Also, I just found out about your videocampus-sachsen-downloader :)

Users of [TUfast](https://github.com/TUfast-TUD/TUfast_TUD) keep requesting this feature. As you have already worked with it, could you implement this feature in javascript (maybe add a download button next to the videos) and create a PR on TUfast. That would be awesome!

**Comment by spyfly** [comment]
@OliEfr your request seems to be completely unrelated to this project, as it does not propose any ideas or changes related to this project. Therefore I am closing this issue. 
I'd suggest opening a issue in your own project.
