### ISSUE TITLE
Funktioniert nicht @ Ubuntu

### ISSUE THREAD

**Issue by TrashFromTheBeginning** [spyfly/videocampus-sachsen-downloader#2]
Servus, leider funktioniert bei mir gar nix keine Ahnung was ich falsch mache. Bin aber auch kein Linux Poweruser.
wäre super wenn du mir helfen könntest.

![2021-09-20 12_38_58-Ubuntu  wird ausgeführt  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91061485/133989715-ffff71b4-bc8b-4cdc-a20b-b86a144127fd.png)

Dann kommt 
![2021-09-20 12_42_31-Ubuntu  wird ausgeführt  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91061485/133989903-a4cb90d0-1787-4591-9726-2558fe6c2eb9.png)

Mit sudo gehts auch nicht.

Wäre nett von dir, wenn du mir hilfst.

**Comment by thrOo** [comment]
Hi,
ich das nette script ohne den install genutzt. (werde es nicht so häufig brauchen, also ist der direkte befehl für mich nicht wichtig.)
Starte den downloader einfach mit:
`python3 vcs-downloader.py`

Hoffe das hilft :)

**Comment by thrOo** [comment]
leider ist der download immer wieder abgebrochen... 
probiere es gerade mit youtube-dl und der m3u8 url (wie im screenshot)

**Comment by spyfly** [comment]
> Servus, leider funktioniert bei mir gar nix keine Ahnung was ich falsch mache. Bin aber auch kein Linux Poweruser. wäre super wenn du mir helfen könntest.
> 
> ![2021-09-20 12_38_58-Ubuntu wird ausgeführt - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91061485/133989715-ffff71b4-bc8b-4cdc-a20b-b86a144127fd.png)
> 
> Dann kommt ![2021-09-20 12_42_31-Ubuntu wird ausgeführt - Oracle VM VirtualBox](https://user-images.githubusercontent.com/91061485/133989903-a4cb90d0-1787-4591-9726-2558fe6c2eb9.png)
> 
> Mit sudo gehts auch nicht.
> 
> Wäre nett von dir, wenn du mir hilfst.

So, das Install Script sollte jetzt gefixt sein, einfach mal die aktuelle Version runterladen.

Nach der Installation könnte eine erneute Anmeldung erforderlich sein, danach funktioniert das Script unter deinem Benutzer.
