### ISSUE TITLE
Abgebrochene Downloads

### ISSUE THREAD

**Issue by spyfly** [spyfly/videocampus-sachsen-downloader#3]
leider ist der download immer wieder abgebrochen... 
probiere es gerade mit youtube-dl und der m3u8 url (wie im screenshot)

_Originally posted by @thrOo in https://github.com/spyfly/videocampus-sachsen-downloader/issues/2#issuecomment-955070156_

Könntest du mir eine Beispiel-URL geben? Ich habe bisher keine abgebrochenen Downloads erlebt.

**Comment by thrOo** [comment]
Hi klar,
https://videocampus.sachsen.de/getMedium/200bcba2e8d1a97ea2fee23dd463f8e1.mp4?1635542626
müsste es gewesen sein. 

hab gerade die Logindaten nicht. um es zu testen. hab es gerade aus der history geholt.

es ging bis ****076.ts und ist dann abgebrochen. (von ca. 1100.ts)
glaube es kam ein 404(http) zurück.

hatte per youtube-dl erfolg beim runterladen. dort habe ich auch vereinzelt 404 gesehen aber das hat er dann einfach neu versucht.

vielleicht müsste bei dir noch eine retry-logik rein

**Comment by spyfly** [comment]
Sollte mit dem neusten Update gefixt sein: https://github.com/spyfly/videocampus-sachsen-downloader/commit/9876bc0b766fc6c96fb942ecc66620daed176f43
